---
- name: "Prepare steps"
  block:

  - name: "Add Node Exporter group"
    ansible.builtin.group:
      name: "{{ node_exporter_group }}"
      state: present
      system: true

  - name: "Add Node Exporter user"
    ansible.builtin.user:
      name: "{{ node_exporter_user }}"
      group: "{{ node_exporter_group }}"
      createhome: false
      system: true
      shell: "/usr/sbin/nologin"

- name: "Get and unarchive Node Exporter"
  block:

  - name: "Get checksum list"
    ansible.builtin.set_fact:
      node_exporter_checksums_fact: "{{ lookup('url', node_exporter_checksum_url, wantlist=True) | list }}"
    until: node_exporter_checksums_fact is search('linux-' + arch + '.tar.gz')
    retries: 5

  - name: "Get checksum to check target archive"
    ansible.builtin.set_fact:
      node_exporter_checksum_fact: "{{ item.split(' ')[0] }}"
    with_items: "{{ node_exporter_checksums_fact }}"
    when:
      - "('linux-' + arch + '.tar.gz') in item"

  - name: "Download Node Exporter binary"
    become: false
    ansible.builtin.get_url:
      url: "{{ node_exporter_url }}"
      dest: "/tmp/{{ node_exporter_archive }}"
      mode: 0644
      checksum: "sha256:{{ node_exporter_checksum_fact }}"
    retries: 5
    delay: 2

  - name: "Unarchive Node Exporter"
    become: false
    ansible.builtin.unarchive:
      src: "/tmp/{{ node_exporter_archive }}"
      dest: "/tmp/"

  run_once: true
  delegate_to: localhost

- name: "Install and start Node Exporter on target servers"
  block:

  - name: "Copy Node Exporter binary to server"
    ansible.builtin.copy:
      src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter"
      dest: "{{ node_exporter_install_dir }}/"
      mode: 0755
      owner: "{{ node_exporter_user }}"
      group: "{{ node_exporter_group }}"

  - name: "Copy systemd unit to server"
    ansible.builtin.template:
      src: node_exporter.service.j2
      dest: /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode: 0644
  notify:
    "restart node exporter"

- name: "Start and enabled Node Exporter service"
  become: true
  ansible.builtin.service:
    name: node_exporter
    state: started
    enabled: true
