---
# handlers file for ansible-role-prometheus
  - name: "Restart Prometheus Node Exporter"
    become: true
    ansible.builtin.service:
      name: node_exporter
      state: restarted
    listen: "restart node exporter"
