---
# handlers file for ansible-role-prometheus
  - name: "Restart Prometheus Node Exporter"
    become: true
    ansible.builtin.systemd:
      daemon_reload: true
      name: node_exporter
      state: restarted
